version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev