version: '3.8'

services:
  frontend:
    build:
      context: ./bloglist-frontend
      dockerfile: dev.Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./bloglist-frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  backend:
    build:
      context: ./bloglist-backend
      dockerfile: dev.Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    volumes:
      - ./bloglist-backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
